### ISSUE TITLE
hi,i get a problem

### ISSUE THREAD

**Issue by wyxxl** [ChrisTheCoolHut/bcheck#1]
![~TVX@4BC P_MAMZEQ_UJRBA](https://user-images.githubusercontent.com/26040426/210029010-a09aff9f-b37f-441d-8c99-10e28a618f03.png)

**Comment by ChrisTheCoolHut** [comment]
Hey I've seen this issue before. One of the latest angr updates broke some of the detection logic. If you use an older published angr version it should work. I'll try to update it to work with the latest angr

**Comment by ChrisTheCoolHut** [comment]
Just pushed up 6bc98b3 which fixes this. Thanks for the bug report!
